[package]
name = "mult_panic"
version = "0.1.0"
authors = ["Alexander Theißen <alex.theissen@me.com>"]
edition = "2018"

[lib]
crate-type = [
	"cdylib",
]

[profile.release]
overflow-checks = true
opt-level = "z"
panic = "abort"
lto = true

[dependencies]
